"""
Add indexes.

Revision ID: d1a9df11343b
Revises: 62dff1150a46
Create Date: 2025-12-30 14:56:27.335328

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d1a9df11343b"
down_revision: str | Sequence[str] | None = "62dff1150a46"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_feature_set_id"), "feature", ["set_id"], unique=False)
    op.create_index(
        op.f("ix_set_ingested_history_set_id"),
        "set_ingested_history",
        ["set_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_set_ingested_history_set_id"), table_name="set_ingested_history"
    )
    op.drop_index(op.f("ix_feature_set_id"), table_name="feature")
    # ### end Alembic commands ###
